### ISSUE TITLE
No build directory 

### ISSUE THREAD

**Issue by DhananjayAshok** [DanielTakeshi/gym-cloth#6]
I follow the installations instructions on an Ubuntu 18.04 system until the example it works fine. but then I get.

```
(py3-cloth) dhananjay@dhananjay-G7-7700:~/Desktop/gym-cloth$ python examples/analytic.py oracle --max_episodes=400 --seed=1336 --tier=1
Yes, cython compiled.

Our result_path:
	/home/dhananjay/Desktop/gym-cloth/examples/../logs/demos-2021-06-25-11-59-pol-oracle-seed-1336-obs-blender-depth-False-rgbd-True-tier1_epis_400.pkl
06-25 11:59:36 cloth_env   : DEBUG    Just re-seeded env to: 8952872158261658479
06-25 11:59:36 cloth_env   : DEBUG    Just re-seeded env to: 1336
Traceback (most recent call last):
  File "examples/analytic.py", line 788, in <module>
    run(args, policy)
  File "examples/analytic.py", line 697, in run
    env.render(filepath=args.render_path)
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/site-packages/gym_cloth-0.0.1-py3.6-linux-x86_64.egg/gym_cloth/envs/cloth_env.py", line 1066, in render
    os.chdir(filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dhananjay/Desktop/gym-cloth/examples/../render/build'

```

**Comment by DhananjayAshok** [comment]
If I create one manually I get a different error:

```
(py3-cloth) dhananjay@dhananjay-G7-7700:~/Desktop/gym-cloth$ mkdir /home/dhananjay/Desktop/gym-cloth/examples/../render/build
(py3-cloth) dhananjay@dhananjay-G7-7700:~/Desktop/gym-cloth$ python examples/analytic.py oracle --max_episodes=400 --seed=1336 --tier=1
Yes, cython compiled.

Our result_path:
	/home/dhananjay/Desktop/gym-cloth/examples/../logs/demos-2021-06-25-12-13-pol-oracle-seed-1336-obs-blender-depth-False-rgbd-True-tier1_epis_400.pkl
06-25 12:13:17 cloth_env   : DEBUG    Just re-seeded env to: 503639421971226832
06-25 12:13:17 cloth_env   : DEBUG    Just re-seeded env to: 1336
Traceback (most recent call last):
  File "examples/analytic.py", line 788, in <module>
    run(args, policy)
  File "examples/analytic.py", line 697, in run
    env.render(filepath=args.render_path)
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/site-packages/gym_cloth-0.0.1-py3.6-linux-x86_64.egg/gym_cloth/envs/cloth_env.py", line 1068, in render
    self.render_proc = subprocess.Popen(["./clothsim"], stdout=dev_null, stderr=dev_null)
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './clothsim': './clothsim'

```

**Comment by DanielTakeshi** [comment]
Hi @DhananjayAshok  thanks for your interest in the code!
Just wanted to check, for your first post, were you able to install the renderer from these instructions:
https://github.com/DanielTakeshi/gym-cloth#renderer-installation
That should create a `build/` directory.
