### ISSUE TITLE
Blender does not exist crashes the simulation

### ISSUE THREAD

**Issue by DhananjayAshok** [DanielTakeshi/gym-cloth#7]
I run the example line and the simulation window pops up as expected. However after a few seconds. 

```
Traceback (most recent call last):
  File "examples/analytic.py", line 788, in <module>
    run(args, policy)
  File "examples/analytic.py", line 708, in run
    obs = env.reset()
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/site-packages/gym_cloth-0.0.1-py3.6-linux-x86_64.egg/gym_cloth/envs/cloth_env.py", line 795, in reset
    obs = self.state
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/site-packages/gym_cloth-0.0.1-py3.6-linux-x86_64.egg/gym_cloth/envs/cloth_env.py", line 204, in state
    img_rgb = self.get_blender_rep('False')
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/site-packages/gym_cloth-0.0.1-py3.6-linux-x86_64.egg/gym_cloth/envs/cloth_env.py", line 281, in get_blender_rep
    str(self.dom_rand_params['specular_max'])
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/dhananjay/miniconda3/envs/py3-cloth/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'blender': 'blender'

```

**Comment by zhangxiaozhier** [comment]
me too!

**Comment by River-mao** [comment]
It seems that the "blender" isn't installed, so you can solve this just by installing "blender" in your conda env.
> (env_name) sudo apt install blender

**Comment by DanielTakeshi** [comment]
I do not install Blender using `sudo apt install`.

**Comment by River-mao** [comment]
> 
That's really weird. But I did solve this problem by installing the **blender** package in ubuntu18.04 platform. I found that this error occurs when this script attempts to open a new **blender** thread, so I guess that this error is essentially due to the lack of **blender** package.
